/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hamdi' at '04/02/17 00:40' with Gradle 2.10
 *
 * @author hamdi, @date 04/02/17 00:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
